name: TowerDefense
version: ${project.version}
main: placeblock.towerdefense.TowerDefense
api-version: 1.17
authors: [ Placeblock ]
description: A TowerDefense Plugin for Minecraft
commands:
  towerdefense:
    description: The Main Tower Defense Command
    aliases:
      - td